version: '3'
services:
  api:
    build: .   # build from local Dockerfile instead of pulling image
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app  # mounts your code inside container
    command: npm run dev  # for development; use 'npm start' for prod